(module core)

((. (require :bufferline) :setup))
(require :plug.lualine_con)
(require :plug.bufferline)
(require :plug.fzf)
(require :plug.indentline)
(require :plug.playground)
(require :plug.startify)
(require :plug.treesitter)
(require :plug.ultisnips)
(require :plug.vimtex)
(require :plug.vimwiki)
